version: '3.8'
services:
  serviarr:
    image: nikollot/serviarr:latest
    container_name: serviarr
    ports:
      - "80:80"
    volumes:
      - ./data:/var/www/html/data  # Pour sauvegarder la configuration
      - /var/run/docker.sock:/var/run/docker.sock # Optionnel : pour gérer Docker
    restart: unless-stopped